# Generated by Django 5.0.7 on 2024-07-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='shop_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.shopuser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='visitor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.visitoruser'),
        ),
    ]
