# Generated by Django 5.0.7 on 2024-08-02 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_shop_user_alter_chatroom_visitor_user_and_more'),
        ('products', '0004_alter_product_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('shop_user', 'visitor_user', 'product')},
        ),
    ]
