# Generated by Django 5.0.7 on 2024-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='프로필사진'),
        ),
    ]
