# Generated by Django 5.0.7 on 2024-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('NEWBIE', '신인'), ('ROOKIE', '후보'), ('SEMIPRO', '주전'), ('PRO', '올스타'), ('MASTER', '국대')], default='NEWBIE', max_length=8, verbose_name='레벨'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manner_score',
            field=models.FloatField(default=0, verbose_name='바로미터'),
        ),
    ]
