# Generated by Django 5.0.7 on 2024-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
