# Generated by Django 5.0.7 on 2024-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('NEWBIE', '뉴비'), ('ROOKIE', '루키'), ('SEMIPRO', '세미프로'), ('PRO', '프로'), ('MASTER', '마스터')], default='NEWBIE', max_length=8, verbose_name='레벨'),
        ),
        migrations.AddField(
            model_name='user',
            name='manner_score',
            field=models.FloatField(default=0, verbose_name='매너지수'),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
