# Generated by Django 5.0.7 on 2024-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_level_alter_user_manner_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=dict, null=True, upload_to='', verbose_name='프로필사진'),
        ),
    ]
