# Generated by Django 5.0.7 on 2024-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_level_user_manner_score_user_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, null=True, verbose_name='프로필사진'),
        ),
    ]
