# Generated by Django 5.0.7 on 2024-07-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhistories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='state',
            field=models.CharField(choices=[('SCHEDULED', '일정확정'), ('CANCELLED', '거래취소'), ('DEAL_COMPLETED', '거래승인'), ('IN_USE', '사용중'), ('RETURNED', '반납완료')], max_length=16, verbose_name='대여 상태'),
        ),
    ]
