# Generated by Django 5.0.7 on 2024-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhistories', '0003_remove_rentalhistory_rental_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='state',
            field=models.CharField(choices=[('SCHEDULED', '일정확정'), ('IN_USE', '사용중'), ('RETURNED', '반납완료')], default='SCHEDULED', max_length=16, verbose_name='대여 상태'),
        ),
    ]
