# Generated by Django 5.0.7 on 2024-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhistories', '0004_alter_rentalhistory_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalhistory',
            name='remaining_days',
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='state',
            field=models.CharField(choices=[('SCHEDULED', '일정확정'), ('IN_USE', '사용중'), ('FINISHED', '반납완료')], max_length=16, verbose_name='대여 상태'),
        ),
    ]
