# Generated by Django 5.0.7 on 2024-07-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhistories', '0004_rentalhistory_rental_days_alter_rentalhistory_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
