# Generated by Django 5.0.7 on 2024-07-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort', models.CharField(max_length=16, verbose_name='카테고리 종류')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='products.category', verbose_name='상위 카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='제품명')),
                ('description', models.CharField(max_length=64, verbose_name='설명')),
                ('long_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='상세설명')),
                ('rental_fee_for_a_day', models.IntegerField(verbose_name='일일 대여료')),
                ('rental_fee_for_a_week', models.IntegerField(verbose_name='일주일 대여료')),
                ('rental_fee_for_a_month', models.IntegerField(blank=True, null=True, verbose_name='한달 대여료')),
                ('rental_period_limit', models.IntegerField(verbose_name='최대 대여가능기간')),
                ('direct_dealing_is_allowed', models.BooleanField(verbose_name='직거래 가능여부')),
                ('direct_dealing_place', models.CharField(max_length=128, verbose_name='희망 직거래 장소')),
                ('delivery_fee_is_included', models.BooleanField(verbose_name='배송비 포함여부')),
                ('delivery_fee', models.IntegerField(verbose_name='배송비')),
                ('views', models.IntegerField(verbose_name='조회수')),
                ('photos', models.JSONField(verbose_name='제품 이미지')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='카테고리')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(verbose_name='owner에 대한 별점평가')),
                ('comment', models.CharField(max_length=128, verbose_name='product에 대한 코멘트')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='제품')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=16, verbose_name='해시태그')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product', verbose_name='제품')),
            ],
        ),
    ]
