# Generated by Django 5.0.7 on 2024-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=32, verbose_name='product에 대한 코멘트'),
        ),
    ]
