# Generated by Django 5.0.7 on 2024-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rental_fee_for_a_month',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rental_period_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='', max_length=64, verbose_name='모델명'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('BEST', '상'), ('GOOD', '중'), ('AVERAGE', '하')], default='', max_length=8, verbose_name='제품 상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='상세설명'),
        ),
    ]
