# Generated by Django 5.0.7 on 2024-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rental_fee_for_a_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='일주일 대여료'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='해시태그'),
        ),
    ]
