# Generated by Django 5.0.7 on 2024-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_direct_dealing_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('BEST', '새 것과 비슷해요'), ('GOOD', '깨끗해요'), ('AVERAGE', '쓸 만해요')], default='', max_length=8, verbose_name='제품 상태'),
        ),
    ]
