# Generated by Django 5.0.7 on 2024-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_rental_fee_for_a_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_fee',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='RENTAL', max_length=8, verbose_name='제품 타입'),
        ),
    ]
