# Generated by Django 5.0.7 on 2024-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='해시태그'),
        ),
    ]
