# Generated by Django 5.0.7 on 2024-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('새 것과 비슷해요', '새 것과 비슷해요'), ('깨끗해요', '깨끗해요'), ('쓸 만해요', '쓸 만해요')], default='', max_length=16, verbose_name='제품 상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='products.tag'),
        ),
    ]
