# Generated by Django 5.0.7 on 2024-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='direct_dealing_place',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='희망 직거래 장소'),
        ),
    ]
