# Generated by Django 5.0.7 on 2024-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_tag_product_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='해시태그'),
        ),
    ]
