# Generated by Django 5.0.7 on 2024-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_direct_dealing_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='모델명'),
        ),
    ]
